image: docker:latest

services:
  - docker:dind

variables:
  IMAGE_NAME: commean/commean.eu
  DOCKER_USERNAME: $DOCKER_USERNAME
  DOCKER_PASSWORD: $DOCKER_PASSWORD

build:
  stage: build
  script:
    - docker build .
  except:
  - tags

deploy:
  stage: deploy
  script:
    - docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
    - docker build -t "${IMAGE_NAME}:${CI_COMMIT_TAG}" .
    - docker push "${IMAGE_NAME}:${CI_COMMIT_TAG}"
  only:
    - tags
